In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [ ]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print(tf.__version__)

2.2.0


In [4]:
dataset = tf.data.Dataset.range(20)
for val in dataset:
   print(val.numpy())

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [9]:
dataset = tf.data.Dataset.range(50)
dataset = dataset.window(10, shift=2)
for window_dataset in dataset:
  # print(window_dataset, end="**\n")
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

0 1 2 3 4 5 6 7 8 9 
2 3 4 5 6 7 8 9 10 11 
4 5 6 7 8 9 10 11 12 13 
6 7 8 9 10 11 12 13 14 15 
8 9 10 11 12 13 14 15 16 17 
10 11 12 13 14 15 16 17 18 19 
12 13 14 15 16 17 18 19 20 21 
14 15 16 17 18 19 20 21 22 23 
16 17 18 19 20 21 22 23 24 25 
18 19 20 21 22 23 24 25 26 27 
20 21 22 23 24 25 26 27 28 29 
22 23 24 25 26 27 28 29 30 31 
24 25 26 27 28 29 30 31 32 33 
26 27 28 29 30 31 32 33 34 35 
28 29 30 31 32 33 34 35 36 37 
30 31 32 33 34 35 36 37 38 39 
32 33 34 35 36 37 38 39 40 41 
34 35 36 37 38 39 40 41 42 43 
36 37 38 39 40 41 42 43 44 45 
38 39 40 41 42 43 44 45 46 47 
40 41 42 43 44 45 46 47 48 49 
42 43 44 45 46 47 48 49 
44 45 46 47 48 49 
46 47 48 49 
48 49 


In [10]:
dataset = tf.data.Dataset.range(50)
dataset = dataset.window(10, shift=2, drop_remainder=True)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

0 1 2 3 4 5 6 7 8 9 
2 3 4 5 6 7 8 9 10 11 
4 5 6 7 8 9 10 11 12 13 
6 7 8 9 10 11 12 13 14 15 
8 9 10 11 12 13 14 15 16 17 
10 11 12 13 14 15 16 17 18 19 
12 13 14 15 16 17 18 19 20 21 
14 15 16 17 18 19 20 21 22 23 
16 17 18 19 20 21 22 23 24 25 
18 19 20 21 22 23 24 25 26 27 
20 21 22 23 24 25 26 27 28 29 
22 23 24 25 26 27 28 29 30 31 
24 25 26 27 28 29 30 31 32 33 
26 27 28 29 30 31 32 33 34 35 
28 29 30 31 32 33 34 35 36 37 
30 31 32 33 34 35 36 37 38 39 
32 33 34 35 36 37 38 39 40 41 
34 35 36 37 38 39 40 41 42 43 
36 37 38 39 40 41 42 43 44 45 
38 39 40 41 42 43 44 45 46 47 
40 41 42 43 44 45 46 47 48 49 


In [12]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
  print(window.numpy())


[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [13]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
for x,y in dataset:
  print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [14]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
for x,y in dataset:
  print(x.numpy(), y.numpy())


[0 1 2 3] [4]
[2 3 4 5] [6]
[1 2 3 4] [5]
[5 6 7 8] [9]
[3 4 5 6] [7]
[4 5 6 7] [8]


In [15]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)
for x,y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())


x =  [[1 2 3 4]
 [0 1 2 3]]
y =  [[5]
 [4]]
x =  [[3 4 5 6]
 [5 6 7 8]]
y =  [[7]
 [9]]
x =  [[4 5 6 7]
 [2 3 4 5]]
y =  [[8]
 [6]]
